cameras:
- allowed_roles:
  - SuperAdmin
  category: Building 1
  enabled: true
  ip: 192.168.100.45
  name: Maintenance_Shop
  onvif_port: 80
  rtsp_url: rtsp://admin:123456@192.168.100.45:554/stream0
  segment_duration: 600
  subcategory: Maintenance
  visible: true
- category: Building 3
  enabled: true
  ip: 192.168.100.10
  name: DBP2_Winders
  rtsp_url: rtsp://admin:123456@192.168.100.10:554/stream0
  subcategory: DBP2
  visible: true
  onvif_port: 80
  segment_duration: 600
  allowed_roles:
  - Supervisor
- category: Building 3
  enabled: true
  ip: 192.168.100.11
  name: DBP2_Unwinder
  rtsp_url: rtsp://admin:123456@192.168.100.11:554/stream0
  subcategory: DBP2
  visible: true
  onvif_port: 80
  segment_duration: 600
  allowed_roles:
  - Supervisor
- name: new
  ip: 192.168.100.13
  rtsp_url: rtsp://192.168.100.13:554/stream0?username=admin&password=E10ADC3949BA59ABBE56E057F20F883E
  onvif_port: 80
  enabled: true
  visible: false
  category: ''
  subcategory: ''
  segment_duration: 600
  allowed_roles:
  - Supervisor
- name: new2
  ip: 192.168.100.14
  rtsp_url: rtsp://192.168.100.14:554/stream0?username=admin&password=E10ADC3949BA59ABBE56E057F20F883E
  onvif_port: 80
  enabled: true
  visible: false
  category: ''
  subcategory: ''
  segment_duration: 600
  allowed_roles:
  - Supervisor
- name: DBP2_Operator
  ip: 192.168.100.12
  rtsp_url: rtsp://192.168.100.12:554/stream0?username=admin&password=E10ADC3949BA59ABBE56E057F20F883E
  onvif_port: 80
  enabled: true
  visible: true
  category: Building 3
  subcategory: DBP2
  segment_duration: 600
  allowed_roles:
  - Supervisor
layout:
  category_order:
  - Building 1
  - Building 2
  - Building 3
  subcategory_order:
    Building 1:
    - Maintenance
    Building 3:
    - DBP2
storage:
  max_size_gb: 5120.0
pending_cameras: []
