mqtt:
  enabled: false
database:
  path: /config/frigate.db
record:
  enabled: true
  alerts:
    retain:
      days: 60
  detections:
    retain:
      days: 60
  continuous:
    days: 30
  motion:
    days: 30
snapshots:
  enabled: true
  retain:
    default: 30
detectors:
  cpu1:
    type: cpu
    num_threads: 2
go2rtc:
  streams:
    Maintenance_Shop:
    - ffmpeg:rtsp://admin:123456@192.168.100.45:554/stream0#video=h264#audio=copy
    DBP2_Winders:
    - ffmpeg:rtsp://admin:123456@192.168.100.10:554/stream0#video=h264#audio=copy
    DBP2_Unwinder:
    - ffmpeg:rtsp://admin:123456@192.168.100.11:554/stream0#video=h264#audio=copy
    new:
    - ffmpeg:rtsp://192.168.100.13:554/stream0?username=admin&password=E10ADC3949BA59ABBE56E057F20F883E#video=h264#audio=copy
    new2:
    - ffmpeg:rtsp://192.168.100.14:554/stream0?username=admin&password=E10ADC3949BA59ABBE56E057F20F883E#video=h264#audio=copy
    DBP2_Operator:
    - ffmpeg:rtsp://192.168.100.12:554/stream0?username=admin&password=E10ADC3949BA59ABBE56E057F20F883E#video=h264#audio=copy
cameras:
  Maintenance_Shop:
    ffmpeg:
      inputs:
      - path: rtsp://admin:123456@192.168.100.45:554/stream0
        roles:
        - record
    record:
      enabled: true
    detect:
      enabled: false
      width: 1920
      height: 1080
    snapshots:
      enabled: true
  DBP2_Winders:
    ffmpeg:
      inputs:
      - path: rtsp://admin:123456@192.168.100.10:554/stream0
        roles:
        - record
    record:
      enabled: true
    detect:
      enabled: false
      width: 1920
      height: 1080
    snapshots:
      enabled: true
  DBP2_Unwinder:
    ffmpeg:
      inputs:
      - path: rtsp://admin:123456@192.168.100.11:554/stream0
        roles:
        - record
    record:
      enabled: true
    detect:
      enabled: false
      width: 1920
      height: 1080
    snapshots:
      enabled: true
  new:
    ffmpeg:
      inputs:
      - path: rtsp://192.168.100.13:554/stream0?username=admin&password=E10ADC3949BA59ABBE56E057F20F883E
        roles:
        - record
    record:
      enabled: true
    detect:
      enabled: false
      width: 1920
      height: 1080
    snapshots:
      enabled: true
  new2:
    ffmpeg:
      inputs:
      - path: rtsp://192.168.100.14:554/stream0?username=admin&password=E10ADC3949BA59ABBE56E057F20F883E
        roles:
        - record
    record:
      enabled: true
    detect:
      enabled: false
      width: 1920
      height: 1080
    snapshots:
      enabled: true
  DBP2_Operator:
    ffmpeg:
      inputs:
      - path: rtsp://192.168.100.12:554/stream0?username=admin&password=E10ADC3949BA59ABBE56E057F20F883E
        roles:
        - record
    record:
      enabled: true
    detect:
      enabled: false
      width: 1920
      height: 1080
    snapshots:
      enabled: true
version: 0.17-0
